trigger:
- main
- feature/*

pool:
  name: 'LocalAgent'

variables:
  buildConfiguration: 'Release'
  artifactName: 'HelloWorldApp'
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isFeature: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')]

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- script: |
    if [ -f version.txt ]; then
      VERSION=$(cat version.txt)
    else
      VERSION="1.0.0"
    fi
    IFS='.' read -r major minor patch <<< "$VERSION"
    patch=$((patch + 1))
    NEW_VERSION="$major.$minor.$patch"
    echo $NEW_VERSION > version.txt
    echo "##vso[task.setvariable variable=buildVersion]$NEW_VERSION"
    echo "Current Version: $VERSION"
    echo "New Version: $NEW_VERSION"
  displayName: 'Increment and print version'

# SonarCloud - ONLY on feature branches
- task: SonarCloudPrepare@1
  condition: eq(variables.isFeature, true)
  displayName: 'Prepare SonarCloud analysis'
  inputs:
    SonarCloud: 'SonarCloudConnection'
    organization: '1bar1'
    scannerMode: 'MSBuild'
    projectKey: '1bar1'
    projectName: 'HelloWorldPipeline'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) /p:Version=$(buildVersion)'

# SonarCloud analyze - ONLY on feature branches
- task: SonarCloudAnalyze@1
  condition: eq(variables.isFeature, true)
  displayName: 'Run SonarCloud analysis'

- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:Version=$(buildVersion)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Upload to Pipeline Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(artifactName)-$(buildVersion)'
    publishLocation: 'Container'

- script: |
    echo "Build completed with version: $(buildVersion)"
    echo "Branch: $(Build.SourceBranchName)"
    echo "Is Feature Branch: $(isFeature)"
  displayName: 'Print build info'